name: "${COMPOSE_NAME}"
services:
  web-server:
    build: .
    command: uv run main.py
    ports:
      - ${COMPOSE_WEB_SERVER_PORT}:8000

  postgres:
    image: postgres:18
    environment:
      POSTGRES_PASSWORD: postgres

  run-migrations:
    build: .
    command: uv run alembic upgrade head

  frontend:
    build: ./frontend
    command: npm run dev
    ports:
      - ${COMPOSE_FRONTEND_PORT}:5173
